#!/usr/bin/env node
// Generates supabase/seed.sql from the demo dataset + controlled vocabularies so the
// seed can never drift from the code. Demo interactions are seeded as 'candidate' —
// they must never appear in the public RLS-visible 'published' set.
import {interactions} from '../src/data/demo.ts';
import {data} from '../src/data/provider.ts';
import {readFileSync, writeFileSync} from 'node:fs';

const vocab=JSON.parse(readFileSync(new URL('../data/controlled-vocabularies.json',import.meta.url),'utf8'));
const q=(s)=>`'${String(s).replaceAll(`'`,`''`)}'`;
const lines=[`-- GENERATED by scripts/generate-seed.mjs — do not edit by hand.`,
`-- Demo seed: every interaction below is DEMO data seeded as interaction_status='candidate'`,
`-- so RLS keeps it invisible to anonymous readers (docs/CURATION_GUIDE.md).`];
lines.push(`delete from interaction_reference; delete from evidence; delete from mimicry_interaction; delete from taxon_synonym; delete from biological_entity;`);
for(const [v,terms] of Object.entries(vocab)){
  if(!Array.isArray(terms)||terms.length===0||typeof terms[0]==='string')continue;
  for(const t of terms)lines.push(`insert into vocabulary_term (vocabulary, term, label, sort_order) values (${q(v)}, ${q(t.term)}, ${q(t.label)}, ${t.sort_order??0}) on conflict (vocabulary, term) do nothing;`);
}
const taxa=data.taxa();
for(const t of taxa){
  const rank=t.name.split(/\s+/).length>=2?'species':(/^[A-Z]/.test(t.name)?'genus':'unresolved higher taxon / functional class');
  const kingdom=t.lineages.split(' · ')[0]??'';
  lines.push(`insert into taxon (scientific_name, canonical_name, name_verbatim, rank, kingdom, taxonomic_status, taxonomic_resolution) select ${q(t.name)}, ${q(t.name)}, ${q(t.name)}, ${q(rank)}, ${q(kingdom)}, 'accepted', 'demo — unresolved' where not exists (select 1 from taxon where scientific_name=${q(t.name)});`);
}
for(const i of interactions){
  const gradeReason=i.evidence==='E0'?'demo record — resemblance only':i.evidence==='E1'?'demo record — author proposal':i.evidence==='E2'?'demo record — ecological support':i.evidence==='E3'?'demo record — experimental/quantitative support':'demo record';
  lines.push(`insert into mimicry_interaction (public_id, mimic_taxon_id, model_taxon_id, receiver_description, interaction_status, knowledge_status, evidence_grade, evidence_grade_reason, mimicry_summary, model_resolution) select ${q(i.id)}, m.id, o.id, ${q(i.receiver)}, 'candidate', ${q(i.knowledge??'reported')}, ${q(i.evidence)}, ${q(gradeReason)}, ${q(i.summary)}, 'demo — unresolved' from taxon m, taxon o where m.scientific_name=${q(i.mimic)} and o.scientific_name=${q(i.model)} on conflict (public_id) do nothing;`);
  for(const r of i.refs??[]){
    lines.push(`insert into reference (title, citation_text) select ${q(r.title)}, ${q(r.title+' [DEMO placeholder]')} where not exists (select 1 from reference where title=${q(r.title)});`);
    lines.push(`insert into interaction_reference (interaction_id, reference_id) select mi.id, rf.id from mimicry_interaction mi, reference rf where mi.public_id=${q(i.id)} and rf.title=${q(r.title)};`);
  }
}
writeFileSync(new URL('../supabase/seed.sql',import.meta.url),lines.join('\n')+'\n');
console.log(`generated supabase/seed.sql — ${taxa.length} taxa, ${interactions.length} candidate interactions`);
