#!/usr/bin/env node
// Generates supabase/seed.sql from the demo dataset + controlled vocabularies so the
// seed can never drift from the code. Demo interactions are seeded as 'candidate' —
// they must never appear in the public RLS-visible 'published' set.
import {interactions} from '../src/data/demo.ts';
import {data} from '../src/data/provider.ts';
import {readFileSync, writeFileSync} from 'node:fs';

const vocab=JSON.parse(readFileSync(new URL('../data/controlled-vocabularies.json',import.meta.url),'utf8'));
const gbifReport=JSON.parse(readFileSync(new URL('../data/reconciliation/gbif.json',import.meta.url),'utf8'));
const q=(s)=>`'${String(s).replaceAll(`'`,`''`)}'`;
const termId=(v,t)=>`TERM:${v.toUpperCase().replace(/[^A-Z0-9]+/g,'_')}:${String(t).toUpperCase().replace(/[^A-Z0-9]+/g,'_')}`;
const lines=[`-- GENERATED by scripts/generate-seed.mjs — do not edit by hand.`,
`-- Demo seed: every interaction below is DEMO data seeded as interaction_status='candidate'`,
`-- so RLS keeps it invisible to anonymous readers (docs/CURATION_GUIDE.md).`];
lines.push(`delete from interaction_reference; delete from evidence; delete from mimicry_interaction; delete from taxon_synonym; delete from biological_entity; delete from system_interaction; delete from mimicry_system; delete from taxon_external_identifier; delete from contributor; delete from contribution;`);
for(const [v,terms] of Object.entries(vocab)){
  if(!Array.isArray(terms)||terms.length===0||typeof terms[0]==='string')continue;
  for(const t of terms)lines.push(`insert into vocabulary_term (vocabulary, term, label, sort_order, public_id, parent_term, definition, version, status) values (${q(v)}, ${q(t.term)}, ${q(t.label)}, ${t.sort_order??0}, ${q(termId(v,t.term))}, ${t.parent?q(t.parent):'null'}, ${t.definition?q(t.definition):'null'}, '1.1', 'accepted') on conflict (vocabulary, term) do nothing;`);
}
const taxa=data.taxa();
taxa.forEach((t,ti)=>{t.__pid='TAXON:'+String(ti+1).padStart(6,'0');});
for(const t of taxa){
  const rank=t.name.split(/\s+/).length>=2?'species':(/^[A-Z]/.test(t.name)?'genus':'unresolved higher taxon / functional class');
  const kingdom=t.lineages.split(' · ')[0]??'';
  lines.push(`insert into taxon (public_id, scientific_name, canonical_name, name_verbatim, rank, kingdom, taxonomic_status, taxonomic_resolution) select ${q(t.__pid)}, ${q(t.name)}, ${q(t.name)}, ${q(t.name)}, ${q(rank)}, ${q(kingdom)}, 'accepted', 'demo — unresolved' where not exists (select 1 from taxon where scientific_name=${q(t.name)});`);
}
// taxon_external_identifier backfill from the GBIF reconciliation report — only for
// matches that really are this name usage (same guard as the vernacular names).
for(const r of gbifReport.results){
  if(!r.gbif_usageKey)continue;
  const canon=(r.gbif_canonical??'').trim().toLowerCase();
  const bare=r.input.replace(/\s*\([^)]*\)\s*$/,'').trim().toLowerCase();
  const ok=!canon||canon===r.input.trim().toLowerCase()||canon===bare;
  if(!ok)continue;
  lines.push(`insert into taxon_external_identifier (taxon_id, authority, external_id, external_url, matched_name, match_type, verified_at) select id, 'GBIF', ${q(String(r.gbif_usageKey))}, ${q('https://www.gbif.org/species/'+r.gbif_usageKey)}, ${q(r.gbif_canonical??r.input)}, ${q(r.matchType)}, now() from taxon where scientific_name=${q(r.input)} on conflict do nothing;`);
}
for(const i of interactions){
  const gradeReason=i.evidence==='E0'?'demo record — resemblance only':i.evidence==='E1'?'demo record — author proposal':i.evidence==='E2'?'demo record — ecological support':i.evidence==='E3'?'demo record — experimental/quantitative support':'demo record';
  lines.push(`insert into mimicry_interaction (public_id, mimic_taxon_id, model_taxon_id, receiver_description, interaction_status, knowledge_status, evidence_grade, evidence_grade_reason, mimicry_summary, model_resolution, model_kind) select ${q(i.id)}, m.id, o.id, ${q(i.receiver)}, 'candidate', ${q(i.knowledge??'reported')}, ${q(i.evidence)}, ${q(gradeReason)}, ${q(i.summary)}, 'demo — unresolved', ${q(i.modelKind??'organism')} from taxon m, taxon o where m.scientific_name=${q(i.mimic)} and o.scientific_name=${q(i.model)} on conflict (public_id) do nothing;`);
  for(const r of i.refs??[]){
    lines.push(`insert into reference (title, citation_text) select ${q(r.title)}, ${q(r.title+' [DEMO placeholder]')} where not exists (select 1 from reference where title=${q(r.title)});`);
    lines.push(`insert into interaction_reference (interaction_id, reference_id, claim_roles) select mi.id, rf.id, ${q('{'+(r.claims??[]).join(',')+'}')}::text[] from mimicry_interaction mi, reference rf where mi.public_id=${q(i.id)} and rf.title=${q(r.title)};`);
  }
}
// demo mimicry_system: the Heliconius Müllerian ring groups the two reciprocal edges —
// the grouping layer above atomic interactions, never a replacement for them.
lines.push(`insert into mimicry_system (public_id, name, description, system_type, notes) values ('SYSTEM:000001', 'Heliconius melpomene/erato Müllerian ring', 'Demo grouping: the two reciprocal co-mimicry edges between H. melpomene and H. erato form one ring. Not a scientific claim — placeholder grouping for the demo dataset.', 'ring', 'synthetic demo grouping — labeled DEMO') on conflict (public_id) do nothing;`);
lines.push(`insert into system_interaction (system_id, interaction_id) select ms.id, mi.id from mimicry_system ms, mimicry_interaction mi where ms.public_id='SYSTEM:000001' and mi.public_id in ('MIMICRY:000007','MIMICRY:000015') on conflict do nothing;`);
writeFileSync(new URL('../supabase/seed.sql',import.meta.url),lines.join('\n')+'\n');
console.log(`generated supabase/seed.sql — ${taxa.length} taxa, ${interactions.length} candidate interactions`);
