#!/usr/bin/env node
// Concatenates migrations 001-007 + the generated seed into ONE paste-ready file:
// docs/supabase-setup.sql — run it in Supabase Dashboard -> SQL Editor (new project).
// Idempotent: a previous partial run may already have created policies, so every
// public-select policy is preceded by "drop policy if exists" and the seed inserts
// are conflict-safe, making the paste safe to re-run.
import {readFileSync,writeFileSync} from 'node:fs';
const migrations=['001_initial.sql','002_scientific_schema.sql','003_model_kind.sql','004_claims_assets_vernacular.sql','005_schema_stabilization.sql','006_evidence_v1.sql','007_public_reads.sql'];
const parts=['-- GENERATED by scripts/supabase-setup.mjs - paste this whole file into the Supabase SQL Editor and run it once.',
'-- It applies migrations 001-007 in order, then loads the demo seed.',
"-- Demo interactions are seeded as interaction_status='candidate': RLS keeps them invisible to anonymous readers."];
for(const m of migrations){
  parts.push('');
  parts.push('-- ==================== '+m+' ====================');
  parts.push('');
  parts.push(readFileSync(new URL('../supabase/migrations/'+m,import.meta.url),'utf8'));
}
parts.push('');
parts.push('-- ==================== seed.sql (generated) ====================');
parts.push('');
parts.push(readFileSync(new URL('../supabase/seed.sql',import.meta.url),'utf8'));
const idem=parts.map(part=>part.replace(/create policy ("[^"]+") on (\w+) for select/g,
  'drop policy if exists $1 on $2;\ncreate policy $1 on $2 for select'));
writeFileSync(new URL('../docs/supabase-setup.sql',import.meta.url),idem.join('\n'));
console.log('docs/supabase-setup.sql written ('+migrations.length+' migrations + seed, idempotent)');
