-- 002_scientific_schema.sql — extends the prototype schema toward the full scientific model (prompt.md PHASE 3)
alter table taxon add column if not exists accepted_name text, add column if not exists authorship text, add column if not exists phylum text, add column if not exists class text, add column if not exists order_name text, add column if not exists family text, add column if not exists genus text, add column if not exists species text, add column if not exists external_source text, add column if not exists external_taxon_id text, add column if not exists taxonomic_resolution text, add column if not exists notes text;
create table if not exists taxon_synonym (id uuid primary key default gen_random_uuid(), taxon_id uuid not null references taxon(id) on delete cascade, synonym_name text not null, synonym_type text, source text, notes text, created_at timestamptz default now());
create table if not exists biological_entity (id uuid primary key default gen_random_uuid(), taxon_id uuid references taxon(id), entity_type text default 'unknown', label text, sex text, life_stage text, anatomical_structure text, signal_description text, notes text, created_at timestamptz default now());
create table if not exists vocabulary_term (id uuid primary key default gen_random_uuid(), vocabulary text not null, term text not null, label text, definition text, sort_order int default 0, unique (vocabulary, term));
alter table mimicry_interaction add column if not exists mimic_entity_id uuid references biological_entity(id), add column if not exists model_entity_id uuid references biological_entity(id), add column if not exists receiver_taxon_id uuid references taxon(id), add column if not exists receiver_resolution text, add column if not exists specific_model_identified boolean, add column if not exists geographic_overlap_status text, add column if not exists curator_notes text, add column if not exists created_by uuid, add column if not exists reviewed_by uuid, add column if not exists reviewed_at timestamptz, add column if not exists published_at timestamptz;
create table if not exists interaction_reference (interaction_id uuid not null references mimicry_interaction(id) on delete cascade, reference_id uuid not null references reference(id), created_at timestamptz default now(), primary key (interaction_id, reference_id));
create table if not exists interaction_geography (id uuid primary key default gen_random_uuid(), interaction_id uuid not null references mimicry_interaction(id) on delete cascade, country text, region text, locality text, latitude numeric, longitude numeric, geographic_scope text, sympatry_status text, geographic_evidence text, notes text, created_at timestamptz default now());
create table if not exists candidate (id uuid primary key default gen_random_uuid(), public_id text unique, proposed_mimic text, proposed_model text, proposed_receiver text, proposed_mimicry_type text, proposed_modality text, proposed_evidence_grade text, reference_id uuid references reference(id), evidence_text text, extraction_confidence numeric, extraction_model text, extraction_prompt_version text, extraction_timestamp timestamptz, raw_extraction jsonb, review_status text default 'pending', review_notes text, created_interaction_id uuid references mimicry_interaction(id), created_at timestamptz default now());
create table if not exists evolutionary_origin (id uuid primary key default gen_random_uuid(), public_id text unique not null, focal_mimic_clade_taxon_id uuid references taxon(id), model_taxon_id uuid references taxon(id), mimicry_type text, inferred_number_of_origins int, inference_method text, phylogeny_source text, analysis_version text, confidence numeric, notes text, created_at timestamptz default now());
create table if not exists interaction_origin (interaction_id uuid not null references mimicry_interaction(id) on delete cascade, origin_id uuid not null references evolutionary_origin(id) on delete cascade, primary key (interaction_id, origin_id));
insert into vocabulary_term (vocabulary, term, label, sort_order) values
 ('mimicry_type','batesian','Batesian mimicry',1),('mimicry_type','mullerian','Müllerian mimicry',2),('mimicry_type','aggressive','Aggressive mimicry',3),('mimicry_type','reproductive','Reproductive mimicry',4),('mimicry_type','sexual_deception','Sexual deception',5),('mimicry_type','brood','Brood mimicry',6),('mimicry_type','egg','Egg mimicry',7),('mimicry_type','social','Social mimicry',8),('mimicry_type','parasitic','Parasitic mimicry',9),('mimicry_type','floral','Floral mimicry',10),('mimicry_type','food_deception','Food deception',11),('mimicry_type','protective','Protective mimicry',12),('mimicry_type','automimicry','Automimicry',13),('mimicry_type','masquerade','Masquerade',14),('mimicry_type','uncertain','Uncertain',15),('mimicry_type','other','Other',16),
 ('signal_modality','visual','Visual',1),('signal_modality','morphological','Morphological',2),('signal_modality','colour','Colour',3),('signal_modality','pattern','Pattern',4),('signal_modality','behavioural','Behavioural',5),('signal_modality','locomotor','Locomotor',6),('signal_modality','acoustic','Acoustic',7),('signal_modality','chemical','Chemical',8),('signal_modality','olfactory','Olfactory',9),('signal_modality','tactile','Tactile',10),('signal_modality','vibrational','Vibrational',11),('signal_modality','multimodal','Multimodal',12),('signal_modality','unknown','Unknown',13),('signal_modality','other','Other',14),
 ('receiver_role','predator','Predator',1),('receiver_role','prey','Prey',2),('receiver_role','pollinator','Pollinator',3),('receiver_role','mate','Mate',4),('receiver_role','host','Host',5),('receiver_role','parasite','Parasite',6),('receiver_role','competitor','Competitor',7),('receiver_role','herbivore','Herbivore',8),('receiver_role','social_partner','Social partner',9),('receiver_role','unknown','Unknown',10),('receiver_role','other','Other',11)
on conflict (vocabulary, term) do nothing;
create index if not exists idx_interaction_mimic on mimicry_interaction(mimic_taxon_id);
create index if not exists idx_interaction_model on mimicry_interaction(model_taxon_id);
create index if not exists idx_interaction_status on mimicry_interaction(interaction_status);
create index if not exists idx_interaction_grade on mimicry_interaction(evidence_grade);
create index if not exists idx_interaction_public_id on mimicry_interaction(public_id);
create index if not exists idx_reference_doi on reference(doi);
create index if not exists idx_evidence_interaction on evidence(interaction_id);
create index if not exists idx_taxon_scientific_name on taxon(scientific_name);
alter table taxon_synonym enable row level security; alter table biological_entity enable row level security; alter table vocabulary_term enable row level security; alter table interaction_reference enable row level security; alter table interaction_geography enable row level security; alter table evolutionary_origin enable row level security; alter table interaction_origin enable row level security; alter table candidate enable row level security;
create policy "public vocabulary terms" on vocabulary_term for select using (true);
create policy "public taxon synonyms" on taxon_synonym for select using (true);
create policy "public biological entities" on biological_entity for select using (true);
create policy "public evolutionary origins" on evolutionary_origin for select using (true);
create policy "public interaction references" on interaction_reference for select using (exists (select 1 from mimicry_interaction i where i.id = interaction_id and i.interaction_status = 'published'));
create policy "public interaction geography" on interaction_geography for select using (exists (select 1 from mimicry_interaction i where i.id = interaction_id and i.interaction_status = 'published'));
create policy "public interaction origins" on interaction_origin for select using (exists (select 1 from mimicry_interaction i where i.id = interaction_id and i.interaction_status = 'published'));
