import {interactions,candidates,systems,type Interaction,type DemoReference,type Candidate,type DemoSystem} from './demo.ts';
import {readFileSync} from 'node:fs';
export type {Interaction,DemoReference,Candidate,DemoSystem};
// Wikimedia Commons photo manifest (generated by `npm run fetch:images`) — attribution
// data is mandatory and must be rendered wherever an image appears.
export type TaxonImage={taxon:string;file:string;title:string;page:string;license:string;licenseUrl:string;artist:string;
 /** stable asset id (AntWeb/Macaulay lesson), e.g. "IMG-0007" */
 id?:string; /** life stage / caste when the source states it — never inferred */
 lifeStage?:string};
let imageManifest:Record<string,TaxonImage>={};
try{imageManifest=(JSON.parse(readFileSync(new URL('../../data/images.json',import.meta.url),'utf8')).images??{}) as Record<string,TaxonImage>;}catch{imageManifest={};}
export const imageFor=(name:string):TaxonImage|undefined=>imageManifest[slugify(name)];
// GBIF reconciliation report (generated by `npm run reconcile:gbif`) — reviewable,
// never rewrites dataset names (docs/TAXONOMY_POLICY.md). Absent file = no matches shown.
export type GbifMatch={input:string;queriedAs:string|null;matchType:string;confidence?:number|null;gbif_usageKey?:number|null;gbif_canonical?:string|null;gbif_rank?:string|null;gbif_kingdom?:string|null;warning?:string|null;note?:string;gbif_classification?:{rank:string;name:string;key?:number}[]};
let gbifResults:GbifMatch[]=[];
try{gbifResults=(JSON.parse(readFileSync(new URL('../../data/reconciliation/gbif.json',import.meta.url),'utf8')).results??[]) as GbifMatch[];}catch{gbifResults=[];}
export const gbifFor=(name:string):GbifMatch|undefined=>gbifResults.find(r=>r.input===name);
export const gbifAll=():GbifMatch[]=>gbifResults;
// Chinese vernacular names (generated by `npm run fetch:vernacular`) — display only;
// the scientific name always stays canonical (docs/TAXONOMY_POLICY.md).
let vernacular:Record<string,{input:string;zh:string|null}>={};
try{vernacular=(JSON.parse(readFileSync(new URL('../../data/reconciliation/vernacular.json',import.meta.url),'utf8')).names??{}) as Record<string,{input:string;zh:string|null}>;}catch{vernacular={};}
export const vernacularZh=(name:string):string|undefined=>vernacular[slugify(name)]?.zh??undefined;
// Live Supabase overlay (v0.4.0): scripts/fetch-live-data.mjs pulls the PUBLIC view
// (RLS: interaction_status='published') into data/live/live.json at build time when
// credentials exist. Absent file, empty database, or an unreachable project all fall
// back to the labeled demo dataset — the build never breaks and never fakes.
type LiveFile={fetched_at:string;published:number;interactions:Interaction[];systems:DemoSystem[]};
let live:LiveFile|undefined;
try{
  const f=JSON.parse(readFileSync(new URL('../../data/live/live.json',import.meta.url),'utf8')) as LiveFile;
  if(f.published>0&&f.interactions?.length)live=f;
}catch{live=undefined;}
export const liveSource=():boolean=>!!live;
export type TaxonSummary={name:string;slug:string;asMimic:number;asModel:number;lineages:string};
export type ReferenceSummary={ref:DemoReference;supports:number};
/** Documented query patterns (prompt.md §48): the live Supabase adapter must answer the
 *  same shapes. Filtering happens in the adapter/server, never by shipping the whole DB. */
export type InteractionQuery={mimic?:string;model?:string;mimicKingdom?:string;modelKingdom?:string;type?:string;minEvidence?:'E0'|'E1'|'E2'|'E3'|'E4';modelKind?:string;crossKingdomOnly?:boolean;page?:number;pageSize?:number};
export type InteractionPage={total:number;page:number;pageSize:number;items:Interaction[]};
export interface DataProvider{
  all():Interaction[];
  byId(publicId:string):Interaction|undefined;
  taxa():TaxonSummary[];
  references():ReferenceSummary[];
  refsFor(publicId:string):DemoReference[];
  interactionsForRef(refId:string):Interaction[];
  candidates():Candidate[];
  /** grouping layer (migration 005): rings/complexes above the atomic edges */
  systems():DemoSystem[];
  interactionsForSystem(publicId:string):Interaction[];
  query(filters:InteractionQuery):InteractionPage;
}
export const slugify=(name:string)=>name.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'');
/** Duplicate policy (prompt.md §46): mimic+model pairs are NOT unique — the same pair may
 *  recur with different receivers, stages, modalities or contexts. This only flags
 *  candidate duplicates for curator review; it never blocks a record. */
export const detectDuplicates=(list:Interaction[])=>{const acc=new Map<string,{pair:string;ids:string[]}>();
  for(const i of list){const key=`${i.mimic} → ${i.model}`;
    if(!acc.has(key))acc.set(key,{pair:key,ids:[]}); acc.get(key)!.ids.push(i.id);}
  return [...acc.values()].filter(x=>x.ids.length>1);};
/** Build a DataProvider over any interaction list — the demo dataset and the live
 *  Supabase overlay share this one implementation, so query/filter semantics are
 *  identical for both. */
export const makeProvider=(ints:Interaction[],systemsList:DemoSystem[],cands:Candidate[]):DataProvider=>({
  all:()=>ints,
  byId:(publicId)=>ints.find(i=>i.id===publicId||i.id.replace(':','-')===publicId),
  taxa:()=>{const acc=new Map<string,{name:string;slug:string;asMimic:number;asModel:number;lineages:Set<string>}>();
    const touch=(name:string,side:'asMimic'|'asModel',lineage:string)=>{let t=acc.get(name);
      if(!t){t={name,slug:slugify(name),asMimic:0,asModel:0,lineages:new Set()};acc.set(name,t);}
      t[side]++; if(lineage)t.lineages.add(lineage);};
    for(const i of ints){const [mk,dk]=i.kingdoms.split(' → ');const a=mk?.trim()??'',b=dk?.trim()??'';
      touch(i.mimic,'asMimic',a); touch(i.model,'asModel',b);}
    return [...acc.values()].map(t=>({...t,lineages:[...t.lineages].sort().join(' · ')}));},
  references:()=>{const acc=new Map<string,ReferenceSummary>();
    for(const i of ints)for(const r of i.refs??[]){
      if(!acc.has(r.id))acc.set(r.id,{ref:r,supports:0}); acc.get(r.id)!.supports++;}
    return [...acc.values()];},
  refsFor:(publicId)=>{const i=ints.find(x=>x.id===publicId||x.id.replace(':','-')===publicId);return i?.refs??[];},
  interactionsForRef:(refId)=>ints.filter(i=>(i.refs??[]).some(r=>r.id===refId)),
  candidates:()=>cands,
  systems:()=>systemsList,
  interactionsForSystem:(publicId)=>{const sys=systemsList.find(s=>s.public_id===publicId);return sys?sys.members.map(m=>ints.find(i=>i.id===m)).filter((x):x is Interaction=>!!x):[];},
  query:(f)=>{const g=(i:Interaction)=>+(i.evidence[1]??0);
    const min=f.minEvidence?+(f.minEvidence[1]):0;
    const hit=ints.filter(i=>(!f.mimic||i.mimic===f.mimic)&&(!f.model||i.model===f.model)
      &&(!f.type||i.type===f.type)&&(g(i)>=min)
      &&(!f.modelKind||i.modelKind===f.modelKind)
      &&(!f.mimicKingdom||i.kingdoms.split(' → ')[0]?.trim()===f.mimicKingdom)
      &&(!f.modelKingdom||i.kingdoms.split(' → ')[1]?.trim()===f.modelKingdom)
      &&(!f.crossKingdomOnly||i.kingdoms.split(' → ')[0]?.trim()!==i.kingdoms.split(' → ')[1]?.trim()&&(i.modelKind??'organism')==='organism'));
    const pageSize=Math.max(1,f.pageSize??20); const page=Math.max(1,f.page??1);
    return {total:hit.length,page,pageSize,items:hit.slice((page-1)*pageSize,page*pageSize)};}
});
export const demoProvider:DataProvider=makeProvider(interactions,systems,candidates);
/** The active provider: the live Supabase overlay when the build fetched published
 *  records, otherwise the labeled demo dataset. */
export const data:DataProvider=live?makeProvider(live.interactions,live.systems,[]):demoProvider;
