import {interactions,candidates,type Interaction,type DemoReference,type Candidate} from './demo.ts';
import {readFileSync} from 'node:fs';
export type {Interaction,DemoReference,Candidate};
// GBIF reconciliation report (generated by `npm run reconcile:gbif`) — reviewable,
// never rewrites dataset names (docs/TAXONOMY_POLICY.md). Absent file = no matches shown.
export type GbifMatch={input:string;queriedAs:string|null;matchType:string;confidence?:number|null;gbif_usageKey?:number|null;gbif_canonical?:string|null;gbif_rank?:string|null;gbif_kingdom?:string|null;warning?:string|null;note?:string;gbif_classification?:{rank:string;name:string;key?:number}[]};
let gbifResults:GbifMatch[]=[];
try{gbifResults=(JSON.parse(readFileSync(new URL('../../data/reconciliation/gbif.json',import.meta.url),'utf8')).results??[]) as GbifMatch[];}catch{gbifResults=[];}
export const gbifFor=(name:string):GbifMatch|undefined=>gbifResults.find(r=>r.input===name);
export const gbifAll=():GbifMatch[]=>gbifResults;
export type TaxonSummary={name:string;slug:string;asMimic:number;asModel:number;lineages:string};
export type ReferenceSummary={ref:DemoReference;supports:number};
/** Documented query patterns (prompt.md §48): the live Supabase adapter must answer the
 *  same shapes. Filtering happens in the adapter/server, never by shipping the whole DB. */
export type InteractionQuery={mimic?:string;model?:string;mimicKingdom?:string;modelKingdom?:string;type?:string;minEvidence?:'E0'|'E1'|'E2'|'E3'|'E4';modelKind?:string;crossKingdomOnly?:boolean;page?:number;pageSize?:number};
export type InteractionPage={total:number;page:number;pageSize:number;items:Interaction[]};
export interface DataProvider{
  all():Interaction[];
  byId(publicId:string):Interaction|undefined;
  taxa():TaxonSummary[];
  references():ReferenceSummary[];
  refsFor(publicId:string):DemoReference[];
  interactionsForRef(refId:string):Interaction[];
  candidates():Candidate[];
  query(filters:InteractionQuery):InteractionPage;
}
export const slugify=(name:string)=>name.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'');
/** Duplicate policy (prompt.md §46): mimic+model pairs are NOT unique — the same pair may
 *  recur with different receivers, stages, modalities or contexts. This only flags
 *  candidate duplicates for curator review; it never blocks a record. */
export const detectDuplicates=(list:Interaction[])=>{const acc=new Map<string,{pair:string;ids:string[]}>();
  for(const i of list){const key=`${i.mimic} → ${i.model}`;
    if(!acc.has(key))acc.set(key,{pair:key,ids:[]}); acc.get(key)!.ids.push(i.id);}
  return [...acc.values()].filter(x=>x.ids.length>1);};
const splitKingdoms=(i:Interaction)=>{const [a,b]=i.kingdoms.split(' → ');return [a?.trim()??'',b?.trim()??''];};
export const demoProvider:DataProvider={
  all:()=>interactions,
  byId:(publicId)=>interactions.find(i=>i.id===publicId||i.id.replace(':','-')===publicId),
  taxa:()=>{const acc=new Map<string,{name:string;slug:string;asMimic:number;asModel:number;lineages:Set<string>}>();
    const touch=(name:string,side:'asMimic'|'asModel',lineage:string)=>{let t=acc.get(name);
      if(!t){t={name,slug:slugify(name),asMimic:0,asModel:0,lineages:new Set()};acc.set(name,t);}
      t[side]++; if(lineage)t.lineages.add(lineage);};
    for(const i of interactions){const [mk,dk]=splitKingdoms(i);
      touch(i.mimic,'asMimic',mk); touch(i.model,'asModel',dk);}
    return [...acc.values()].map(t=>({...t,lineages:[...t.lineages].sort().join(' · ')}));},
  references:()=>{const acc=new Map<string,ReferenceSummary>();
    for(const i of interactions)for(const r of i.refs??[]){
      if(!acc.has(r.id))acc.set(r.id,{ref:r,supports:0}); acc.get(r.id)!.supports++;}
    return [...acc.values()];},
  refsFor:(publicId)=>{const i=interactions.find(x=>x.id===publicId||x.id.replace(':','-')===publicId);return i?.refs??[];},
  interactionsForRef:(refId)=>interactions.filter(i=>(i.refs??[]).some(r=>r.id===refId)),
  candidates:()=>candidates,
  query:(f)=>{const g=(i:Interaction)=>+(i.evidence[1]??0);
    const min=f.minEvidence?+(f.minEvidence[1]):0;
    const hit=interactions.filter(i=>(!f.mimic||i.mimic===f.mimic)&&(!f.model||i.model===f.model)
      &&(!f.type||i.type===f.type)&&(g(i)>=min)
      &&(!f.modelKind||i.modelKind===f.modelKind)
      &&(!f.mimicKingdom||i.kingdoms.split(' → ')[0]?.trim()===f.mimicKingdom)
      &&(!f.modelKingdom||i.kingdoms.split(' → ')[1]?.trim()===f.modelKingdom)
      &&(!f.crossKingdomOnly||i.kingdoms.split(' → ')[0]?.trim()!==i.kingdoms.split(' → ')[1]?.trim()&&(i.modelKind??'organism')==='organism'));
    const pageSize=Math.max(1,f.pageSize??20); const page=Math.max(1,f.page??1);
    return {total:hit.length,page,pageSize,items:hit.slice((page-1)*pageSize,page*pageSize)};}
};
/** Single swap point for a future live adapter (e.g. Supabase); pages import only `data`. */
export const data:DataProvider=demoProvider;
